name: keda-runner
on:
  
  workflow_dispatch:   

jobs:
  my_job:
    runs-on: [ keda-runner ]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Sleep for 10 minutes
        run: sleep 1800s
        shell: bash

    
