name: My GitHub Action

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Define the manual trigger event

jobs:
  my_job:
    runs-on: keda-runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Sleep for 10 minutes
        run: |
          echo "Sleeping for 10 minutes..."
          sleep 600
          echo "Finished sleeping."

      - name: Your Other Steps
        # Add your other workflow steps here
